# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'APIExample' do
  
  use_frameworks!
  pod 'Floaty', '~> 4.2.0'  
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'AgoraRtcEngine_Special_iOS', '3.5.0.203.mpk'
end

target 'Agora-ScreenShare-Extension' do
  pod 'AgoraRtcEngine_Special_iOS', '3.5.0.203.mpk'
  use_frameworks!
end
