# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'APIExample' do
  
  use_frameworks!
  pod 'Floaty', '~> 4.2.0'  
  pod 'AGEVideoLayout', '~> 1.0.2'
#   pod 'AgoraNGSDK', :path => 'sdk'
end

target 'Agora-ScreenShare-Extension' do

  use_frameworks!
#   pod 'AgoraRtcEngine_iOS', '3.5.0'
end
